.gitignore
components/wookie-cache-memcache/pom.xml
pom.xml

Just attempted to build the project using Scala Eclipse. Got a few errors. This is intended to fix them.
Added Eclipse specific files to .gitignore
Added m2e plugin config that ignores incremental-build (Eclipse doesn't like that plugin)
Added explicit link to Twitter public repository

Eclipse and initial build improvements

---

components/wookie-kafka/src/main/scala/com/webtrends/harness/component/kafka/actor/KafkaProducer.scala

Last changes from harness. To get producer using keys

---

components/wookie-socko/src/main/scala/com/webtrends/harness/component/socko/utils/CORSSupportDirectives.scala

Support null origin

---

components/wookie-socko/src/main/scala/com/webtrends/harness/component/socko/utils/CORSSupportDirectives.scala

Support null string

---

components/wookie-kafka/src/main/scala/com/webtrends/harness/component/kafka/actor/KafkaConsumerProxy.scala
components/wookie-kafka/src/main/scala/com/webtrends/harness/component/kafka/actor/PartitionConsumerWorker.scala
components/wookie-kafka/src/main/scala/com/webtrends/harness/component/kafka/health/CoordinatorHealth.scala
components/wookie-socko/src/main/scala/com/webtrends/harness/component/socko/route/SockoRoutes.scala

Latest harness changes for common collection

---

components/wookiee-kafka/src/main/scala/com/webtrends/harness/component/kafka/actor/OffsetManager.scala
components/wookiee-zookeeper/src/main/scala/com/webtrends/harness/component/zookeeper/ZookeeperActor.scala
components/wookiee-zookeeper/src/main/scala/com/webtrends/harness/component/zookeeper/ZookeeperService.scala

Harness 2228bd3c3223f9e74d48b464ede940f8445c47f8

---

components/wookiee-kafka/src/main/scala/com/webtrends/harness/component/kafka/health/KafkaWriterHealthCheck.scala

H 9bf1918380a130580449e6e876a546ab36af11ea

Make producer timeout configurable

---

wookiee-core/src/main/scala/com/webtrends/harness/health/ApplicationHealth.scala
wookiee-core/src/main/scala/com/webtrends/harness/health/HealthComponent.scala
wookiee-core/src/main/scala/com/webtrends/harness/utils/Json.scala

Harness bc3584a6e6d512cc5891873a83155bac78884436

Health check order

---

components/wookiee-socko/src/main/scala/com/webtrends/harness/component/socko/SockoHttpWorker.scala
components/wookiee-socko/src/main/scala/com/webtrends/harness/component/socko/route/SockoRoutes.scala

H 1f22d52c119318aa042f110f125d9c727ad4c522

URI too long error code

---

components/wookiee-zookeeper/src/main/scala/com/webtrends/harness/component/zookeeper/ZookeeperActor.scala
components/wookiee-zookeeper/src/main/scala/com/webtrends/harness/component/zookeeper/discoverable/Discoverable.scala
components/wookiee-zookeeper/src/main/scala/com/webtrends/harness/component/zookeeper/discoverable/DiscoverableCommandHelper.scala
components/wookiee-zookeeper/src/main/scala/com/webtrends/harness/component/zookeeper/discoverable/DiscoverableService.scala

Allowing a developer to specifically set the address of the ServiceInstance for the command/service that they are making discoverable.

Setting address on ServiceInstance

---

components/wookiee-zookeeper/src/main/scala/com/webtrends/harness/component/zookeeper/Curator.scala

@Crashfreak If you get errors around ServiceInstance tomorrow when you try to deploy then this fixed them for me

Change to fix case where instance would not get properly deserialized in case where we use discoverable

---

docs/Commands.md
wookiee-core/src/main/scala/com/webtrends/harness/command/Command.scala
wookiee-core/src/main/scala/com/webtrends/harness/command/CommandHelper.scala
wookiee-core/src/main/scala/com/webtrends/harness/command/CommandManager.scala

@pcross616 @stotten @ladinu @malibuworkcrew @davis20 @mjwallin1 
Change Commands to return instances of a trait instead of a case class.

Create BaseCommandResponse trait

---

wookiee-core/src/main/scala/com/webtrends/harness/command/CommandBeanExtraction.scala
wookiee-core/src/test/scala/com/webtrends/harness/command/CommandBeanExtractionSpec.scala
wookiee-test/src/test/scala/com/webtrends/harness/TestHarnessSpec.scala

@stotten @pdxito @ladinu @malibuworkcrew

Bean extraction - make default values optional

---

wookiee-core/src/main/scala/com/webtrends/harness/command/CommandBeanExtraction.scala
wookiee-core/src/test/scala/com/webtrends/harness/command/CommandBeanExtractionSpec.scala
wookiee-core/src/test/scala/com/webtrends/harness/http/InternalHttpSpec.scala

Fixed optional bug

---

wookiee-core/src/main/scala/com/webtrends/harness/service/ServiceManager.scala
wookiee-test/src/main/scala/com/webtrends/harness/service/test/TestHarness.scala

Fixing old test harness bug where we could get multiple services created

---

wookiee-core/src/main/scala/com/webtrends/harness/command/CommandHelper.scala
wookiee-core/src/main/scala/com/webtrends/harness/command/CommandManager.scala

Only check a Command's health if needed

---

pom.xml

Revert "Revert to akka 2.3.12"

---

wookiee-core/src/main/scala/com/webtrends/harness/command/BaseCommand.scala
wookiee-core/src/main/scala/com/webtrends/harness/command/Command.scala
wookiee-core/src/main/scala/com/webtrends/harness/command/CommandLike.scala

See https://github.com/Webtrends/wookiee-akka-http/pull/15

adding BaseCommand trait

---

pom.xml
wookiee-core/src/main/scala/com/webtrends/harness/app/HarnessActor.scala
wookiee-core/src/main/scala/com/webtrends/harness/health/ActorHealth.scala

* On shutdown we would throw an error if there is no service up, only a component
* On shutdown we would throw an error if we shutdown before init was complete
* On shutdown we would not shutdown main actors if we didn't finish init of children
* Entire health check would fail if one component failed to report
@pcross616 Should be safe to go in and get a new release

Fixes for a few bugs:

---

wookiee-core/src/main/scala/com/webtrends/harness/app/HarnessActor.scala
wookiee-core/src/main/scala/com/webtrends/harness/health/ActorHealth.scala

A Couple of NPE Bug Fixes

---

wookiee-core/src/main/scala/com/webtrends/harness/command/Command.scala
wookiee-core/src/test/scala/com/webtrends/harness/command/CommandSpec.scala

Make command matching case insensitive

---

wookiee-core/pom.xml
wookiee-core/src/main/scala/com/webtrends/harness/authentication/CIDRRules.scala
wookiee-core/src/main/scala/com/webtrends/harness/health/HealthCheckProvider.scala
wookiee-core/src/main/scala/com/webtrends/harness/service/ServiceLoader.scala
wookiee-core/src/test/scala/com/webtrends/harness/http/CIDRRulesSpec.scala

@pcross616 Most changes are just cleanup

Versions outputting correctly and consistently for health check and services

---

wookiee-core/src/main/scala/com/webtrends/harness/component/ComponentManager.scala

@pcross616 Should be safe to go

Preventing NPE that happens on quick TestHarness runs

---

wookiee-core/src/main/scala/com/webtrends/harness/app/Harness.scala
wookiee-core/src/main/scala/com/webtrends/harness/command/CommandManager.scala
wookiee-core/src/main/scala/com/webtrends/harness/component/ComponentHelper.scala
wookiee-core/src/main/scala/com/webtrends/harness/service/ServiceManager.scala

Mainly encountered during TestHarness runs and shutdowns.

NPE, None.get, head of empty list bug fixes

---

README.md
examples/basic-service/pom.xml
examples/basic-service/readme.md
examples/basic-service/src/main/resources/application.conf
examples/basic-service/src/main/resources/logback.xml
examples/basic-service/src/main/scala/com/wookiee/basic/BasicService.scala
examples/basic-service/src/test/scala/com/wookiee/basic/BasicServiceTest.scala
pom.xml
wookiee-core/pom.xml
wookiee-core/src/main/scala/com/webtrends/harness/app/Harness.scala
wookiee-core/src/main/scala/com/webtrends/harness/app/HarnessActor.scala
wookiee-core/src/main/scala/com/webtrends/harness/app/HarnessActorSystem.scala
wookiee-core/src/main/scala/com/webtrends/harness/component/Component.scala
wookiee-core/src/main/scala/com/webtrends/harness/component/ComponentManager.scala
wookiee-core/src/main/scala/com/webtrends/harness/config/ConfigWatcherActor.scala
wookiee-core/src/main/scala/com/webtrends/harness/health/HealthCheckActor.scala
wookiee-core/src/main/scala/com/webtrends/harness/logging/LoggingActor.scala
wookiee-core/src/main/scala/com/webtrends/harness/service/Service.scala
wookiee-core/src/main/scala/com/webtrends/harness/service/ServiceManager.scala
wookiee-test/pom.xml
wookiee-test/src/main/scala/com/webtrends/harness/service/test/BaseSpecTest.scala
wookiee-test/src/main/scala/com/webtrends/harness/service/test/TestHarness.scala

* Created new fully working basic-service in the examples directory with setup readme and unit test
* Altered poms to bring along more useful dependencies
* Fixed some NPE bugs in main harness classes
* Wired up config watching fully
* Added config watching instructions to README
* New traits to easily hook into test harness
* Stop missing the Ready message
* Logging turned down in many cases
* No more errors on shutdown

 Documentation Updates and Bug Fixes

---

pom.xml
wookiee-core/src/main/scala/com/webtrends/harness/app/HarnessActor.scala
wookiee-core/src/main/scala/com/webtrends/harness/logging/Logging.scala
wookiee-core/src/main/scala/com/webtrends/harness/service/Service.scala
wookiee-core/src/test/scala/com/webtrends/harness/logging/LoggerSpec.scala
wookiee-test/src/main/scala/com/webtrends/harness/service/test/util/ActorWaitHelper.scala

* NPE fix on shutdown
* Helper logging method and spec to log on failure
* Await actor by ref

Logging and Waiting Improvements

---

wookiee-core/src/main/scala/com/webtrends/harness/app/Harness.scala
wookiee-core/src/main/scala/com/webtrends/harness/component/Component.scala
wookiee-test/src/main/scala/com/webtrends/harness/service/test/TestComponent.scala
wookiee-test/src/main/scala/com/webtrends/harness/service/test/TestHarness.scala
wookiee-test/src/main/scala/com/webtrends/harness/service/test/TestSystemActor.scala
wookiee-test/src/test/scala/com/webtrends/harness/TestHarnessSpec.scala

Also prevention of CRITICAL errors with unhandled messages for SystemReady and PrepareForShutdown

Harness Log no longer an Option

---

pom.xml
wookiee-core/pom.xml
wookiee-core/src/main/scala/com/webtrends/harness/app/HarnessActor.scala

* `running` is no longer an option....
* scala-stm to 0.8

Scala Version to 2.11.12

---

.travis.yml
wookiee-core/src/main/scala/com/webtrends/harness/HarnessConstants.scala
wookiee-core/src/main/scala/com/webtrends/harness/health/HealthCheckActor.scala
wookiee-core/src/test/scala/com/webtrends/harness/health/HealthCheckActorSpec.scala

Needs some feedback on logging output format.

Health logging

---

pom.xml

bumps akka to fix some compatibility issues we're seeing with new akka-http version
oh yeah, and also to be good citizens

Akka version bump

---

wookiee-core/src/main/scala/com/webtrends/harness/utils/LocalizedString.scala
wookiee-core/src/test/scala/com/webtrends/harness/utils/LocalizedStringSpec.scala

Added support for multiple locales.
Updated test cases.

Localization

---

wookiee-core/src/main/scala/com/webtrends/harness/utils/Localizable.scala
wookiee-core/src/test/scala/com/webtrends/harness/utils/LocalizedStringSpec.scala

Localizable  trait added to support localizable arguments.

Localizable trait added.

---

wookiee-metrics/src/main/scala/com/oracle/infy/wookiee/metrics/WookieeMetricsService.scala
wookiee-metrics/src/main/scala/com/oracle/infy/wookiee/metrics/impl/WookieeMetricsReporterNoOpImpl.scala

so a metrics registry can be provided by the caller

Add new register methods to WookieeMetricsService

---

wookiee-core/src/main/scala/com/webtrends/harness/component/Extension.scala
wookiee-core/src/main/scala/com/webtrends/harness/utils/Localizable.scala

Add an Extension base class for enabling extension development.

Add Extension base class

---

wookiee-core/src/main/scala/com/webtrends/harness/utils/LocalizedString.scala

Accept class loader for resource bundle loading.

Accept class loader for resource bundle loading

---

VERSION
wookiee-functional-metrics/src/main/scala/com/oracle/infy/wookiee/functional/metrics/core/WookieeMetrics.scala
wookiee-functional-metrics/src/main/scala/com/oracle/infy/wookiee/functional/metrics/impl/WookieeMetricsImpl.scala
wookiee-functional-metrics/src/main/scala/com/oracle/infy/wookiee/functional/metrics/impl/WookieeMetricsNoOpImpl.scala
wookiee-functional-metrics/src/main/scala/com/oracle/infy/wookiee/functional/metrics/impl/WookieeMetricsReporterNoOpImpl.scala
wookiee-functional-metrics/src/main/scala/com/oracle/infy/wookiee/functional/metrics/model/Metric.scala
wookiee-functional-metrics/src/main/scala/com/oracle/infy/wookiee/functional/metrics/model/WookieeRegistry.scala
wookiee-grpc-tests/src/test/scala/com/oracle/infy/wookiee/metrics/tests/MetricsTest.scala

Add `guage[A]` method and fix `WookieeMetricsNoOpImpl`

Add gauge and fix WookieeMetricsNoOpImpl

---

wookiee-core/src/main/scala/com/oracle/infy/wookiee/health/HealthCheckProvider.scala
wookiee-core/src/test/scala/com/oracle/infy/wookiee/health/HealthCheckProviderSpec.scala

Fix format issues so master can build

Scalafmt fix

---

VERSION
wookiee-core/src/main/scala/com/oracle/infy/wookiee/app/HarnessActor.scala
wookiee-core/src/main/scala/com/oracle/infy/wookiee/health/HealthCheckProvider.scala

Adding the exception handling for timeout checks

Healthcheck fix

---

VERSION
project/Deps.scala

Updated netty version due to vulnerabilities.

Update dependency version

---

VERSION
wookiee-core/src/main/scala/com/oracle/infy/wookiee/component/ComponentManager.scala

Corrected the order of loading components as it is verifying WebManager Mediator Instance id before loading components

Debug component loading
